### ISSUE TITLE
Can you change P3D to OPENGL

### ISSUE THREAD

**Issue by alvarobyrne** [ojack/geodomos#1]
At https://github.com/ojack/geodomos/blob/master/GEODOMOS/GEODOMOS.pde#L34

**Comment by ojack** [comment]
yes -- will push when I get a stable version. I cant't find any documentation on OPENGL render mode---what is the difference between it and P3D? (only dound: https://processing.org/tutorials/rendering/)

**Comment by alvarobyrne** [comment]
I managed to change mine to P3D. Initially couldn't.
